export const productsData = [
  {
    id: 1,
    sku: 1198765678987,
    title: "sphynx Tie Dye Grey Tshirt",
    quantity: 1,
    description: "sphynx Tie Dye Grey",
    availableSizes: ["","X", "L", "XL", "XXl"],
    price: 10,
    isFreeShipping: true,
  },

  {
    id: 2,
    sku: 18987235789876,
    title: "Danger Knife Grey Tshirt",
    quantity: 1,
    description: "Danger Knife Grey",
    availableSizes: ["","X", "M", "L"],
    price: 14.9,
    isFreeShipping: true,
  },

  {
    id: 3,
    sku: 1987654678987,
    title: "White DGK Script Tee",
    quantity: 1,
    description: "White DGK Script",
    availableSizes: ["","X", "M", "L"],
    price: 14.9,
    isFreeShipping: true,
  },

  {
    id: 4,
    sku: 21987656789876,
    title: "Born On The Street Tshirt",
    quantity: 1,
    description: "Born On The Street",
    availableSizes: ["","XL"],
    price: 25.9,
    isFreeShipping: false,
  },

  {
    id: 5,
    sku: 173482988987,
    title: "Tso 3D Short Sleeve",
    quantity: 1,
    description: "Tso 3D Short",
    availableSizes: ["","X", "L", "XL"],
    price: 10.9,
    isFreeShipping: false,
  },

  {
    id: 6,
    sku: 113209868987,
    title: "Man Tie Dye Cinza Grey Tshirt",
    quantity: 1,
    description: "Man Tie Dye Cinza Grey",
    availableSizes: ["","XL", "XXL"],
    price: 49.9,
    isFreeShipping: false,
  },

  {
    id: 7,
    sku: 451616789872,
    title: "Crazy Monkey Black Tshirt",
    quantity: 1,
    description: "Crazy Monkey Black",
    availableSizes: ["","S"],
    style: "Preto com listras brancas",
    price: 22.5,
    isFreeShipping: true,
  },

  {
    id: 8,
    sku: 2110098678987,
    title: "Tso 3D Black Tshirt",
    quantity: 1,
    description: "",
    availableSizes: ["","XL"],
    style: "azul escuro",
    price: 18.7,
    isFreeShipping: false,
  },

  {
    id: 9,
    sku: 7673156789873,
    title: "Crazy Monkey Grey",
    quantity: 1,
    description: "",
    availableSizes: ["","L", "XL"],
    price: 134.9,
    isFreeShipping: true,
  },
];
